# Generated by Django 5.1.3 on 2025-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_historyrecord_additional_physical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecord',
            name='additional_physical',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='common_performance',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='disease_tendency',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='health_advice',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='physical_characteristics',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='physical_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='psychological_characteristics',
            field=models.TextField(default=''),
        ),
    ]
