# Generated by Django 5.1.3 on 2025-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_alter_historyrecord_additional_physical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyrecord",
            name="face_diagnosis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historyrecord",
            name="tongue_diagnosis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
